name: 'zendesk'
version: '0.1'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
test-paths: ["test"]
data-paths: ["data"]
log-path: "logs"

models:
  zendesk:
    stitch:
      enabled: true
      vars:
        organizations_table: # schema.table
        tickets_table:       # schema.table
        ticket_events_table: # schema.table
        users_table:         # schema.table
